name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4

      # ideally it should be done by `opam install . --deps-only` but right now
      # we have opam 1.x in the repo, and I'm not very optimistic to even try it
      - run: opam install cairo2 calendar conf-dbm eliom ocsigen-i18n ocsigen-ppx-rpc ocsigen-toolkit ocsipersist-dbm pgocaml_ppx syndic

      - name: Compiling simple
        run: opam exec -- make -C simple all

      - name: Compiling extended
        run: opam exec -- make -C extended all
