name: Main workflow

on:
  push:
  pull_request:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14"
          allow-prerelease-opam: true

      # ideally it should be done by `opam install . --deps-only` but right now
      # we have opam 1.x in the repo, and I'm not very optimistic to even try it
      - run: opam install eliom ocsigen-toolkit cairo2 ocsipersist-dbm calendar syndic conf-dbm

      - name: Compiling simple
        run: opam exec -- make all
        working-directory: simple

      - name: Compiling extended
        run: opam exec -- make all
        working-directory: extended
